name: wiredash
description: Wiredash is an interactive user feedback tool for Flutter apps including Promoter Score.
version: 1.7.1
homepage: https://wiredash.io
repository: https://github.com/wiredashio/wiredash-sdk
issue_tracker: https://github.com/wiredashio/wiredash-sdk/issues

topics:
  - feedback
  - user-feedback
  - bug-reporting
  - crash-reporting
  - nps

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  clock: ^1.1.0
  collection: ">=1.15.0 <2.0.0"
  file: ">=6.0.0 <8.0.0"
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ">=0.13.0 <2.0.0"
  http_parser: ">=4.0.0 <5.0.0"
  intl: ">=0.16.0 <2.0.0" # whatever "sdk: flutter" depends on
  material_color_utilities: ">=0.1.2 <1.0.0"
  path_provider: ">=2.0.0 <3.0.0"
  shared_preferences: '>=2.0.0 <3.0.0'

dev_dependencies:
  fake_async: any
  flutter_test:
    sdk: flutter
  lint: '>=1.10.0 <3.0.0'
  spot: ^0.3.1
  test: ^1.21.0
  transparent_image: ^2.0.0

flutter:
  assets:
    - packages/wiredash/assets/images/logo_white.png

  plugin:
    platforms:
      android:
        default_package: wiredash
      ios:
        default_package: wiredash
      linux:
        default_package: wiredash
      macos:
        default_package: wiredash
      web:
        default_package: wiredash
      windows:
        default_package: wiredash

  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Wirecons
      fonts:
        - asset: lib/assets/fonts/Wirecons.ttf
