name: wiredash
description: Wiredash is an interactive user feedback tool for Flutter apps.
version: 0.2.0
homepage: https://wiredash.io
repository: https://github.com/wiredashio/wiredash-sdk

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  file: ^5.2.1
  http: ^0.12.0
  http_parser: ^3.1.0
  path_provider: ^1.6.14
  provider: ">=3.0.0 <5.0.0"
  shared_preferences: ^0.5.6

dev_dependencies:
  lint: ^1.2.0
  fake_async: ^1.1.0
  flutter_test:
    sdk: flutter
  test: any
  transparent_image: ^1.0.0
  mockito: any

flutter:
  assets:
    - packages/wiredash/assets/images/logo_footer.png
    - packages/wiredash/assets/images/logo_grey.png
    - packages/wiredash/assets/images/logo_white.png
    - packages/wiredash/assets/images/pen.png

  fonts:
    - family: LexendDeca
      fonts:
        - asset: lib/assets/fonts/LexendDeca-Regular.ttf
    - family: wiredash-icons
      fonts:
        - asset: lib/assets/fonts/Wiredash-Icons.ttf
