name: wiredash
description: Wiredash is an interactive user feedback tool for Flutter apps.
version: 0.6.0-nullsafety.1
homepage: https://wiredash.io
repository: https://github.com/wiredashio/wiredash-sdk

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.24.0-8.0.pre.341"

dependencies:
  file: ">=6.0.0-0 <7.0.0"
  flutter:
    sdk: flutter
  http: ">=0.13.0-0 <0.15.0"
  http_parser: ">=4.0.0-0 <5.0.0"
  path_provider: ">=2.0.0-0 <3.0.0"
  shared_preferences: '>=0.5.6 <2.0.0'
  meta: ^1.0.0

dev_dependencies:
  fake_async: any
  flutter_test:
    sdk: flutter
  lint: ^1.5.0
  test: ^1.16.0-nullsafety
  transparent_image: ^2.0.0-nullsafety.0

flutter:
  assets:
    - packages/wiredash/assets/images/logo_footer.png
    - packages/wiredash/assets/images/logo_grey.png
    - packages/wiredash/assets/images/logo_white.png
    - packages/wiredash/assets/images/pen.png

  plugin:
    platforms:
      android:
        default_package: wiredash
      ios:
        default_package: wiredash
      linux:
        default_package: wiredash
      macos:
        default_package: wiredash
      web:
        default_package: wiredash

  fonts:
    - family: LexendDeca
      fonts:
        - asset: lib/assets/fonts/LexendDeca-Regular.ttf
    - family: wiredash-icons
      fonts:
        - asset: lib/assets/fonts/Wiredash-Icons.ttf
