name: wiredash_theme_editor
description: Editor to create Wiredash themes
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0 <4.0.0"

dependencies:
  device_frame: ^1.0.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  google_fonts: ^2.0.0

  wiredash:
    path: ../../

dev_dependencies:
  lint: ^1.0.0

flutter:
  uses-material-design: true
