name: Nightly

on:
  workflow_dispatch:
  schedule:
    # Every night at 03:00
    - cron: '0 3 * * *'

jobs:
  minVersion:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cirruslabs/flutter:3.0.0
    steps:
      - uses: actions/checkout@v3
        with:
          ref: stable
      - name: Flutter version
        run: flutter doctor -v
      - name: Download dependencies
        run: |
          sudo --preserve-env=PATH env flutter packages get
          cd examples/theming && sudo --preserve-env=PATH env flutter packages get
      - name: Test
        run: sudo --preserve-env=PATH env flutter test
      - name: Build
        run: cd examples/theming && sudo --preserve-env=PATH env flutter build web

  stable:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cirruslabs/flutter:stable
    steps:
      - uses: actions/checkout@v3
        with:
          ref: stable
      - name: Flutter version
        run: flutter doctor -v
      - name: Download dependencies
        run: |
          sudo --preserve-env=PATH env flutter packages get
          cd examples/theming && sudo --preserve-env=PATH env flutter packages get
      - name: Test
        run: sudo --preserve-env=PATH env flutter test
      - name: Build
        run: cd examples/theming && sudo --preserve-env=PATH env flutter build web

  beta:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cirruslabs/flutter:beta
    steps:
      - uses: actions/checkout@v3
        with:
          ref: beta
      - name: Flutter version
        run: flutter doctor -v
      - name: Download dependencies
        run: |
          sudo --preserve-env=PATH env flutter packages get
          cd examples/theming && sudo --preserve-env=PATH env flutter packages get
      - name: Test
        run: sudo --preserve-env=PATH env flutter test
      - name: Build
        run: cd examples/theming && sudo --preserve-env=PATH env flutter build web

  latest:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cirruslabs/flutter:latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: beta
      - name: Flutter version
        run: flutter doctor -v
      - name: Download dependencies
        run: |
          sudo --preserve-env=PATH env flutter packages get
          cd examples/theming && sudo --preserve-env=PATH env flutter packages get
      - name: Test
        run: sudo --preserve-env=PATH env flutter test
      - name: Build
        run: cd examples/theming && sudo --preserve-env=PATH env flutter build web
